export const MESSAGE = {
  AUTH_ERROR: '请先登录',
  INVALID_TOKEN: '登录信息已过期，请重新登录',
  RATE_LIMIT_EXCEEDED: '请求过于频繁，请稍后再试',
  INVALID_PARAMS: '参数错误',
  INTERNAL_SERVER_ERROR: '服务器错误',
  USER_NOT_FOUND: '用户不存在',
  LOGIN_ERROR: '登录失败',
  UNKNOWN_ERROR: '未知错误',
  PASSWORD_ERROR: '密码错误',
  INVALID_CODE: '验证码错误',
  VIDEO_NOT_FOUND: '视频不存在',
  FAVORITE_FOLDER_NOT_FOUND: '收藏夹不存在',
  FAVORITE_EXIST: '已收藏',
  FOLDER_EXIST: '收藏夹已存在',
  NOT_FOUND: '不存在',
  NOT_PERMISSION: '没有权限',
  FEED_NOT_FOUND: '动态不存在',
}
